---
title: "R Notebook"
output: html_notebook
---

1.Installing and Loading Required Packages

```{r}
install.packages("readxl")
library(readxl)
library(dplyr)
library(tidyr)
```

2.Importing the WHO Air Quality Dataset

```{r}
install.packages("readxl")
library(readxl)

```

```{r}
air_df <- read_excel("C:/R_coursework/who_ambient_air_quality_database_version_2024_(v6.1) (1).xlsx",sheet = "Update 2024 (V6.1)")

#Database is provided as a multi sheet Excel workbook. The main air pollution measurements are located in the"Update 2024 (V6.1)" sheet, while the other sheets provide metadata about countries and indicators.
```

3.Reviewing the data set
```{r}
head(air_df)
str(air_df)
```

4.Create new data frame with suitable columns
```{r}
air_df1 <- air_df %>%
  select(who_region,iso3,country_name,city,year,pm10_concentration,pm25_concentration,no2_concentration,latitude,longitude,population)
 
air_df1 
```

5.Finding most suitable air

```{r}
air_df1[air_df1 == "NA"] <- NA    
```
```{r}
missing_summary <- data.frame(
  Column = colnames(air_df1),
  Missing_Count = colSums(is.na(air_df1)),
  Missing_Percent = round(colMeans(is.na(air_df1)) * 100, 2)
)


print(missing_summary)
```

6.Selecting Key Air Quality Indicators (PM10)
```{r}
air_df2 <- air_df1 %>%
  select(who_region,iso3,country_name,city,year,pm10_concentration)

air_df2
```


7.Calculating Annual Mean PM10 per Country
```{r}
air_df3 <- air_df2 %>%
  mutate(pm10_concentration = as.numeric(pm10_concentration))%>%
           
  filter(!is.na(pm10_concentration)) %>%    
  group_by( iso3, who_region,country_name, year) %>%
  
  summarise(mean_pm10 = mean(pm10_concentration, na.rm = TRUE))

air_df3 

```

8.choosing suitable year

```{r}



air_df_wide <- air_df3 %>%
  pivot_wider(
    names_from = year,           
    values_from = mean_pm10,
     names_glue = "pm10_values_in_{year}"
  )%>%
  arrange(who_region, country_name)

air_df_wide
```


```{r}
year_cols <- paste0("pm10_values_in_", 2010:2022)


year_sum_table <- data.frame(
  Years = 2010:2022,
  Missing_count = sapply(air_df_wide[, year_cols], function(x) sum(is.na(x))),
  Missing_percentage = sapply(air_df_wide[, year_cols], function(x) mean(is.na(x)) * 100)
)

year_sum_table
```
